apiVersion: v1
kind: Secret
metadata:
  name: plausible-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  SECRET_KEY_BASE: {{ .Values.secretKeyBase | quote }}
  SMTP_USER: {{ .Values.env.mailer.user | quote }}
  SMTP_PASSWORD: {{ .Values.env.mailer.password | quote }}
  DATABASE_URL: "ecto://postgres:{{ .Values.postgres.password }}@{{ .Values.env.database.host }}:{{ .Values.env.database.port }}/{{ .Values.env.database.name }}"
  CLICKHOUSE_DATABASE_URL: "http://{{ .Values.env.clickhouse_user }}:{{ .Values.env.clickhouse_password }}@{{ .Values.env.clickhouse.host }}:{{ .Values.env.clickhouse.port }}/{{ .Values.env.clickhouse.database }}"