apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-ingress-patcher
  namespace: plausible
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-ingress-patcher-binding
  namespace: plausible
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: cert-manager
roleRef:
  kind: Role
  name: cert-manager-ingress-patcher
  apiGroup: rbac.authorization.k8s.io